server:
  port: 8003
spring:
  application:
    name: colin-eureka-server
eureka:
  instance:
    hostname: replicamain
  client:
    service-url:
      defaultZone: http://127.0.0.1:8002/eureka
    fetch-registry: true
    register-with-eureka: true